DROP DATABASE IF EXISTS College;

CREATE DATABASE College;

USE College;

/* 
   Below we create the tables into which we will load
   the data generated by college_normalization.py
*/

CREATE TABLE Universities (
  unit_id 			  int NOT NULL, 
  inst_name 	TEXT, 
  city 	VARCHAR(200), 
  state VARCHAR(50),
  url 			  VARCHAR(200),
  num_branches			TINYINT, 
  control 			  TINYINT, 
  adm_rate	FLOAT, 
  currently_operating  TINYINT,
  PRIMARY KEY (unit_id)

);

CREATE TABLE Test_Scores (
	unit_id				int NOT NULL,
	act_midpoint			float,
	sat_avg				float,
    PRIMARY KEY (unit_id)

);

CREATE TABLE Demographics(
	unit_id 				int NOT NULL,
	ug_degree_seeking_enrollment int,
	total_ug_enrollment int,
	percent_first_generation	 	float,
	avg_age_of_entry				int,
	percent_over_23_at_entry		float,
	percent_female 		float,
	median_family_income			int,
	median_household_income			int,
    PRIMARY KEY (unit_id)
);

CREATE TABLE Program_Percentages(
	unit_id 				int NOT NULL,
	pcip_1						float,
    pcip_3						float,
    pcip_4						float,
    pcip_5						float,
    pcip_9						float,
    pcip_10						float, 
	pcip_11						float,
	pcip_12						float,
    pcip_13						float,
    pcip_14						float,
	pcip_15						float,
	pcip_16						float,
    pcip_19						float,
	pcip_22						float,
    pcip_23						float,
    pcip_24						float,
	pcip_25						float,
	pcip_26						float,
	pcip_27						float,
    pcip_29						float,
	pcip_30						float,
	pcip_31						float,
	pcip_38						float,
	pcip_39						float,
	pcip_40						float,
	pcip_41						float,
	pcip_42						float,
	pcip_43						float,
	pcip_44						float,
	pcip_45						float,
	pcip_46						float,
	pcip_47						float,
	pcip_48						float,
	pcip_49						float,
	pcip_50						float,
	pcip_51						float,
    pcip_52						float,
	pcip_54						float,
    PRIMARY KEY (unit_id)
);

-- drop table Costs;

CREATE TABLE Costs(
		unit_id 									int NOT NULL,
        avg_net_price_public						int,
        avg_net_price_private						int,
		avg_cost_of_attendance						int,
        avg_cost_of_attendance_program_year			int,
        in_state_tuition_and_fees					int,
        out_of_state_tuition_and_fees				int,
        tuition_revenue_per_full_time_student		int	,
		expenditures_per_full_time_student			int,
        avg_faculty_salary							int,
        PRIMARY KEY (unit_id)

);

CREATE TABLE Earnings(
		unit_id 				int NOT NULL,
        number_not_working_6_years_after int,
        number_working_6_years_after 		int,
        mean_earnings_6_years_after 		int,	
		median_earnings_6_years_after		int,
        percentile_25_earnings_6_years_after  int,
        percentile_75_earnings_6_years_after	int,
        standard_deviation_earnings_6_years_after	int,
        number_not_working_10_years_after			int,
        number_working_10_years_after			int,	
		mean_earnings_10_years_after			int,
        median_earnings_10_years_after			int,
        percentile_25_earnings_10_years_after	int,
       percentile_75_earnings_10_years_after	int,
	   standard_deviation_earnings_10_years_after	int,
		PRIMARY KEY (unit_id)

);

CREATE TABLE Specific_CIP_Codes(
	cipcode								int,
	cipdesc								VARCHAR(200),
	PRIMARY KEY (cipcode)
);

CREATE TABLE Broad_CIP_Areas(
	cip_2_digit	TINYINT,
	broad_subject_area VARCHAR(200),
	PRIMARY KEY (cip_2_digit)
);

CREATE TABLE Degrees_Offered(
            unit_id								int,
			cipcode								int,
            credlev								TINYINT,
            number_not_working_2_years_after 	int,
			number_working_2_years_after		int,	
			median_earnings_2_years_after 		int,
            FOREIGN KEY (unit_id) REFERENCES Universities(unit_id),
            FOREIGN KEY (cipcode) REFERENCES Specific_CIP_Codes(cipcode)

);


